<?php

return [
    'regimenes_fiscales' => [
        '601' => '601 - General de Ley Personas Morales',
        '603' => '603 - Personas Morales con Fines no Lucrativos',
        '605' => '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios',
        '606' => '606 - Arrendamiento',
        '607' => '607 - Regimen de Enajenacion o Adquisicion de Bienes',
        '608' => '608 - Demas ingresos',
        '610' => '610 - Residentes en el Extranjero sin Establecimiento Permanente en Mexico',
        '611' => '611 - Ingresos por Dividendos (socios y accionistas)',
        '612' => '612 - Personas Fisicas con Actividades Empresariales y Profesionales',
        '614' => '614 - Ingresos por intereses',
        '615' => '615 - Regimen de los ingresos por obtencion de premios',
        '616' => '616 - Sin obligaciones fiscales',
        '620' => '620 - Sociedades Cooperativas de Produccion que optan por diferir sus ingresos',
        '621' => '621 - Incorporacion Fiscal',
        '622' => '622 - Actividades Agricolas, Ganaderas, Silvicolas y Pesqueras',
        '623' => '623 - Opcional para Grupos de Sociedades',
        '624' => '624 - Coordinados',
        '625' => '625 - Regimen de las Actividades Empresariales con ingresos a traves de Plataformas Tecnologicas',
        '626' => '626 - Regimen Simplificado de Confianza',
    ],

    'usos_cfdi' => [
        'G01' => 'G01 - Adquisicion de mercancias',
        'G02' => 'G02 - Devoluciones, descuentos o bonificaciones',
        'G03' => 'G03 - Gastos en general',
        'I01' => 'I01 - Construcciones',
        'I02' => 'I02 - Mobiliario y equipo de oficina por inversiones',
        'I03' => 'I03 - Equipo de transporte',
        'I04' => 'I04 - Equipo de computo y accesorios',
        'I05' => 'I05 - Dados, troqueles, moldes, matrices y herramental',
        'I06' => 'I06 - Comunicaciones telefonicas',
        'I07' => 'I07 - Comunicaciones satelitales',
        'I08' => 'I08 - Otra maquinaria y equipo',
        'D01' => 'D01 - Honorarios medicos, dentales y gastos hospitalarios',
        'D02' => 'D02 - Gastos medicos por incapacidad o discapacidad',
        'D03' => 'D03 - Gastos funerales',
        'D04' => 'D04 - Donativos',
        'D05' => 'D05 - Intereses reales efectivamente pagados por creditos hipotecarios',
        'D06' => 'D06 - Aportaciones voluntarias al SAR',
        'D07' => 'D07 - Primas por seguros de gastos medicos',
        'D08' => 'D08 - Gastos de transportacion escolar obligatoria',
        'D09' => 'D09 - Depositos en cuentas para el ahorro, primas que tengan como base planes de pensiones',
        'D10' => 'D10 - Pagos por servicios educativos',
        'S01' => 'S01 - Sin efectos fiscales',
        'CP01' => 'CP01 - Pagos',
        'CN01' => 'CN01 - Nomina',
    ],
];
